### ISSUE TITLE
error starting up fresh install on ios

### ISSUE THREAD

**Issue by dylang** [agrcrobles/react-native-web-workspace#1]
Hi, thanks for creating this! I've been using lerna+react and looking for examples of somebody using it with react native. 

I ran into an error running both mobile and web:
<img width="915" alt="screen shot 2017-05-22 at 10 45 59 am" src="https://cloud.githubusercontent.com/assets/51505/26314468/110fb95e-3edc-11e7-8822-f0a59adde823.png">

I used `yarn` instead of `npm`, ran `yarn bootstrap`, had issues with both web and native.

**Comment by agrcrobles** [comment]
Hey @dylang thanks for reporting this!
looks like it is an issue in ios, is it also happening when running only the web dev server?

**Comment by dylang** [comment]
Both ios and the web server, the 404 on the left is from trying the web server.

**Comment by isaacagaba** [comment]
Thanks for the creation of this repo. I have been able to make the web and android working but ios gives the same error as mentioned above.

**Comment by jribeiro** [comment]
I've opened a PR to fix this. Either way you can also get the same example as Android & Web in iOS by editing `mobile/index.ios.js` and replacing:
```js
import { 
	MyApp
} from 'components';

AppRegistry.registerComponent('linking', () => MyApp);
```

by:
```js
import NavigationPlayground from 'react-navigation-playground';
AppRegistry.registerComponent('linking', () => NavigationPlayground);
```

**Comment by agrcrobles** [comment]
That looks great @jribeiro 

Thanks for contributing!
