### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by Jekiwijaya** [agrcrobles/react-native-web-workspace#7]
I create a new package: https://github.com/Jekiwijaya/react-navigation-browser-history-helpers
to maintain browser history for react-navigation in web.

I want to ask your permission. I want to create a modify this project to used as an example in that repository. Is it bother you? Thank you.

**Comment by agrcrobles** [comment]
Sure! Can you explain in detail what is the goal of react-navigation-browser-history-helpers?
Can it be used along with [createBrowserApp.js on universal](https://github.com/ericvicenti/universe/blob/master/universal/src/react-navigation-web/createBrowserApp.js) ?

**Comment by Jekiwijaya** [comment]
wow... hmm.. I never see that before. Looks like it's pretty same.

the goal is places in web platform. Like for your example, the url is integrated. So people can back, and refresh and open same screen.
